---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
    service: cart
    project: acmeshop
spec:
  ports:
    - name: http-cart
      protocol: TCP
      port: 5000
  selector:
    app: cart
    service: cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
    service: cart
    project: acmeshop
spec:
  selector:
    matchLabels:
      app: cart
      service: cart
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
        service: cart
        project: acmeshop
    spec:
      volumes:
      - name: cart-data
        emptyDir: {}
      containers:
      - image: acmeshop-cart
        name: cart
        env:
        - name: REDIS_HOST
          value: 'cart-redis.acmeshop.cloud'
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: password
        - name: REDIS_PORT
          value: '6379'
        - name: CART_PORT
          value: '5000'
        ports:
        - containerPort: 5000
          name: http-cart
        volumeMounts:
        - mountPath: "/data"
          name: "cart-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
