---
apiVersion: v1
kind: Service
metadata:
  name: order-mongo
  labels:
    app: order-mongo
    service: order-mongo
    project: acmeshop
spec:
  ports:
    - port: 27017
      name: mongo-order
      protocol: TCP
  selector:
    app: order-mongo
    service: order-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongo
  labels:
    app: order-mongo
    service: order-mongo
    project: acmeshop
spec:
  selector:
    matchLabels:
      app: order-mongo  # has to match .spec.template.metadata.labels
      service: order-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: order-mongo  # has to match .spec.selector.matchLabels
        service: order-mongo
        project: acmeshop
    spec:
      containers:
        - name: order-mongo
          image: mongo
          resources:
            {}
          ports:
            - name: mongo-order
              containerPort: 27017
              protocol: "TCP"
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: 'mongoadmin'
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-mongo-pass
                key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      volumes:
        - name: mongodata
          emptyDir: {}
#        - name: mongodata
#          persistentVolumeClaim:
#            claimName: mongodata
