apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: acmefit-catalog
    service: catalog
spec:
  ports:
    - name: http-catalog
      protocol: TCP
      port: 8082
  selector:
    app: acmefit-catalog
    service: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: acmefit-catalog
    service: catalog
spec:
  selector:
    matchLabels:
      app: acmefit-catalog
      service: catalog
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit-catalog
        service: catalog
    spec:
      volumes:
      - name: acmefit-catalog-data
        emptyDir: {}
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog:latest
        imagePullPolicy: "Always"
        name: catalog
        env:
        - name: GIN_MODE
          value: 'release'
        - name: CATALOG_DB_HOST
          value: 'catalog-mongo.acmeshop.cloud'
        - name: CATALOG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catalog-mongo-pass
              key: password
        - name: CATALOG_DB_PORT
          value: '27017'
        - name: CATALOG_DB_USERNAME
          value: 'mongoadmin'
        - name: CATALOG_PORT
          value: '8082'
        - name: CATALOG_VERSION
          value: 'v1'
        - name: USERS_HOST
          value: 'users.acmeshop.cloud'
        - name: USERS_PORT
          value: '8083'
        - name: JAEGER_AGENT_HOST
          value: 'jaeger-agent.acmeshop.cloud'
        - name: JAEGER_AGENT_PORT
          value: '6831'
        ports:
        - containerPort: 8082
          name: catalog
        volumeMounts:
        - mountPath: "/data"
          name: "acmefit-catalog-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
