---
apiVersion: v1
kind: Secret
metadata:
  name: redis-pass
type: Opaque
data:
  password: Vk13YXJlMTIzIQ== #cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-mongo-pass
type: Opaque
data:
  password: Vk13YXJlMTIzIQ== #cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-mongo-pass
type: Opaque
data:
  password: Vk13YXJlMTIzIQ== #cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: users-mongo-pass
type: Opaque
data:
  password: Vk13YXJlMTIzIQ== #cGFzc3dvcmQ=
---
apiVersion: v1
data:
  password: Vk13YXJlMTIzIQ== #cGFzc3dvcmQ=
kind: Secret
metadata:
  name: users-redis-pass
type: Opaque
---

